New command line interface (#10)
* New command line arguments

- Ignore "-s" and drop it
- Expect the .spec file as first argument
- Passthrough any other argument to rpmbuild

Added new YUM_ARGS environment variable, to download additional build
dependencies, enable additional build repos etc.

* New IMAGE environment variable

Select the builder image by overriding the default one with an IMAGE env variable.

Adapt makerpms builder invocation to skip "-s" flag.

* Fix end-of-build error

E.g.:

    Installing janus-gateway.spec
    error: janus-gateway.spec cannot be installed

* Add COMMAND environment variable

* Fix docs and build RPMs

* Support YUM_ARGS in podman builds

* Suppress warning for legacy flag usage

nethesis/dev#5836